[package]
name = "unicornd-client"
version = "0.1.0"
authors = ["Gilberto Bertin <me@jibi.io>"]
license = "WTFPL"
description = "Client library for unicornd"
repository  = "https://github.com/jibi/rust-unicornd-client"
